local colors = require "assets.colors"

return {
  NavicIconsConstant = { bg = colors.none },
  NavicIconsFunction = { bg = colors.none },
  NavicIconsIdentifier = { bg = colors.none },
  NavicIconsField = { bg = colors.none },
  NavicIconsVariable = { bg = colors.none },
  NavicIconsSnippet = { bg = colors.none },
  NavicIconsText = { bg = colors.none },
  NavicIconsType = { bg = colors.none },
  NavicIconsKeyword = { bg = colors.none },
  NavicIconsMethod = { bg = colors.none },
  NavicIconsConstructor = { bg = colors.none },
  NavicIconsFolder = { bg = colors.none, fg = colors.yellow },
  NavicIconsModule = { bg = colors.none },
  NavicIconsProperty = { bg = colors.none },
  NavicIconsEnum = { bg = colors.none },
  NavicIconsClass = { bg = colors.none },
  NavicIconsFile = { bg = colors.none },
  NavicIconsInterface = { bg = colors.none },
  NavicIconsColor = { bg = colors.none },
  NavicIconsReference = { bg = colors.none },
  NavicIconsEnumMember = { bg = colors.none },
  NavicIconsStruct = { bg = colors.none },
  NavicIconsValue = { bg = colors.none },
  NavicIconsEvent = { bg = colors.none },
  NavicIconsOperator = { bg = colors.none },
  NavicIconsTypeParameter = { bg = colors.none },
  NavicIconsNamespace = { bg = colors.none },
  NavicIconsPackage = { bg = colors.none },
  NavicIconsString = { bg = colors.none },
  NavicIconsNumber = { bg = colors.none },
  NavicIconsBoolean = { bg = colors.none },
  NavicIconsArray = { bg = colors.none },
  NavicIconsObject = { bg = colors.none },
  NavicIconsKey = { bg = colors.none },
  NavicIconsNull = { bg = colors.none },
  NavicText = { fg = colors.white, bg = colors.none },
  NavicSeparator = { bg = colors.none },
}
