local M = {
  apple = {
    [[                                              ]],
    [[                           .8                 ]],
    [[                         .888                 ]],
    [[                       .8888'                 ]],
    [[                       .8888'                 ]],
    [[                       888'                   ]],
    [[                      8'                      ]],
    [[          .88888888888. .88888888888.         ]],
    [[      .8888888888888888888888888888888.       ]],
    [[    .8888888888888888888888888888888888.      ]],
    [[    .&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'       ]],
    [[    &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'         ]],
    [[    &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'          ]],
    [[    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:           ]],
    [[    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:           ]],
    [[    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%.          ]],
    [[    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%.         ]],
    [[    `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%.       ]],
    [[    `00000000000000000000000000000000000'     ]],
    [[     `000000000000000000000000000000000'      ]],
    [[       `0000000000000000000000000000000'      ]],
    [[         `###########################'        ]],
    [[           `#######################'          ]],
    [[             `#########''########'            ]],
    [[               `""""""'  `"""""'              ]],
    [[                                              ]],
  },
  neofetch = {
    [[                                                                              ]],
    [[                      'c.                                                     ]],
    [[                    ,xNMM.                                                    ]],
    [[                  .OMMMMo                                                     ]],
    [[                  OMMM0,                            Apple M1 Pro             ]],
    [[         .;looddo:' looolloddol;.                                             ]],
    [[       cKMMMMMMMMMMMMNWMMMMMMMMMM0:                 macOS 13.5.2             ]],
    [[     .KMMMMMMMMMMMMMMMMMMMMMMMMWd.                                            ]],
    [[     XMMMMMMMMMMMMMMMMMMMMMMMMMX.                   19.24 GiB / 32.00 GiB    ]],
    [[    ;MMMMMMMMMMMMMMMMMMMMMMMMMM:                                              ]],
    [[    :MMMMMMMMMMMMMMMMMMMMMMMMMM:                    yabai                    ]],
    [[    .MMMMMMMMMMMMMMMMMMMMMMMMMMX.                                             ]],
    [[     kMMMMMMMMMMMMMMMMMMMMMMMMMMWd.                 kitty / tmux             ]],
    [[     .XMMMMMMMMMMMMMMMMMMMMMMMMMMMMk                                          ]],
    [[      .XMMMMMMMMMMMMMMMMMMMMMMMMMMK.                235 brew                 ]],
    [[        kMMMMMMMMMMMMMMMMMMMMMMMMd                                            ]],
    [[          'MMMMMMMMWXXWMMMMMMMk.                                              ]],
    [[            .coooc,.   .,cooo:.                                       ]],
    [[                                                                              ]],
  },
}

return M
