local colors = require "custom.assets.colors"

return {
  Fugit2FloatTitle = { fg = colors.orange },
  Fugit2MenuHead = { fg = colors.magenta },
  Fugit2Heading = { fg = colors.magenta },
  Fugit2Header = { fg = colors.red },
  Fugit2Hash = { fg = colors.yellow },
  Fugit2BlameDate = { fg = colors.green },
  Fugit2GraphDate = { fg = colors.green },
  Fugit2Author = { fg = colors.blue },
  Fugit2BranchHead = { fg = colors.magenta },
  Fugit2ObjectId = { fg = colors.yellow },
  Fugit2Branch1 = { fg = colors.red },
  Fugit2Branch2 = { fg = colors.orange },
  Fugit2Branch3 = { fg = colors.yellow },
  Fugit2Branch4 = { fg = colors.green },
  Fugit2Branch5 = { fg = colors.blue },
  Fugit2Branch6 = { fg = colors.cyan },
  Fugit2Branch7 = { fg = colors.magenta },
  Fugit2Branch8 = { fg = colors.red },
  Fugit2Branch9 = { fg = colors.orange },
  Fugit2Tag1 = { bg = colors.red, fg = colors.black },
  Fugit2Tag2 = { bg = colors.orange, fg = colors.black },
  Fugit2Tag3 = { bg = colors.yellow, fg = colors.black },
  Fugit2Tag4 = { bg = colors.green, fg = colors.black },
  Fugit2Tag5 = { bg = colors.blue, fg = colors.black },
  Fugit2Tag6 = { bg = colors.cyan, fg = colors.black },
  Fugit2Tag7 = { bg = colors.magenta, fg = colors.black },
  Fugit2Tag8 = { bg = colors.maroon, fg = colors.black },
  Fugit2Tag9 = { bg = colors.forest, fg = colors.black },
  -- Fugit2AuthorEmail = "Label",
  -- Fugit2HelpHeader = "Label",
  -- Fugit2HelpTag = "Tag",
  -- Fugit2UntrackedHeading = "PreCondit",
  -- Fugit2UnstagedHeading = "Macro",
  -- Fugit2StagedHeading = "Include",
  -- Fugit2MessageHeading = "diffAdded",
  -- Fugit2Modifier = "Type",
  -- Fugit2Ignored = "Ignore",
  -- Fugit2Unstaged = "diffRemoved",
  -- Fugit2Staged = "diffAdded",
  -- Fugit2Modified = "Constant",
  -- Fugit2Unchanged = "",
  -- Fugit2Untracked = "Error",
  -- Fugit2Instruction = "Type",
  -- Fugit2Stop = "Function",
  -- Fugit2SymbolicRef = "Function",
  -- Fugit2Count = "Number",
  -- Fugit2Insertions = "diffAdded",
  -- Fugit2Deletions = "diffRemoved",
  -- Fugit2Match = "Type",
  -- Fugit2WindowHelp = "Comment",
  -- Fugit2MenuKey = "PreProc",
  -- Fugit2MenuArgOff = "Comment",
  -- Fugit2MenuArgOn = "Number",
  -- Fugit2FloatTitle = "@parameter",
  -- Fugit2RebasePick = "diffAdded", -- green
  -- Fugit2RebaseDrop = "diffRemoved", -- red
  -- Fugit2RebaseSquash = "Type", -- yellow
  -- Fugit2BlameBorder = "Comment",
}
